{
 "title": "Example Fedora Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "POST Resource Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"POST\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])/rate(http_server_requests_seconds_count{method=\"POST\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=~\".*_ERROR\"}[1m])"
    }
   ]
  },
  {
   "title": "GET Resource Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])/rate(http_server_requests_seconds_count{method=\"GET\",uri=\"/fcrepo/rest/{path: .*}\"}[1m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "DB Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_db_seconds_bucket[1m])) by (le, db, operation))",
     "legendFormat": "{{db}} {{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_db_seconds_sum[1m])/rate(fcrepo_db_seconds_count[1m])",
     "legendFormat": "{{db}} {{operation}} avg"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{cause}} avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(jvm_gc_pause_seconds_bucket[1m])) by (le, cause))",
     "legendFormat": "{{cause}} p99"
    }
   ]
  },
  {
   "title": "OCFL Session Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_storage_ocfl_session_seconds_bucket[1m])) by (le, operation))",
     "legendFormat": "{{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_storage_ocfl_session_seconds_sum[1m])/rate(fcrepo_storage_ocfl_session_seconds_count[1m])",
     "legendFormat": "{{operation}} avg"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "OCFL Object Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_storage_ocfl_object_seconds_bucket[1m])) by (le, operation))",
     "legendFormat": "{{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_storage_ocfl_object_seconds_sum[1m])/rate(fcrepo_storage_ocfl_object_seconds_count[1m])",
     "legendFormat": "{{operation}} avg"
    }
   ]
  }
 ]
}